export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const REQUEST_ROUTE = '/request'
export const DEPARTMENT_ROUTE = '/department'
export const MAIN_ROUTE = '/'